# 端口
server:
    port: 8099

spring: 
    # 数据源配置
    datasource: 
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://110.40.199.128:3306/wxdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: rsAC9Q4p
        # 是否打开sql监控台  (生产环境请务必关闭此选项) 
        druid: 
            stat-view-servlet:
                enabled: true
            web-stat-filter: 
                enabled: true
            filter:
                config:
                    enabled: true

    # redis配置 
    redis:
        # Redis数据库索引（默认为0）
        database: 1
        # Redis服务器地址
        host: 110.40.199.128
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: rsAC9Q4p
        # 连接超时时间（毫秒）
        timeout: 5000ms
        lettuce:
            pool:
                # 连接池最大连接数
                max-active: 200
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
                # 连接池中的最大空闲连接
                max-idle: 10
                # 连接池中的最小空闲连接
                min-idle: 0
        jedis:
            pool:
                max-active: 200
                max-wait: -1ms
                max-idle: 10
                min-idle: 0

    # 项目自定义配置
    myconfig:
        # 本项目部署到的服务器域名（文件上传等等模块  要用到）
        domain: http://127.0.0.1:8099
